library(dplyr)
library(ggplot2)
## Exploratory data analysis
## Looking at the data set, we realized that there are differente variables which we want to look deeper into : Biocapacity and Ecological footprint. 
## Biocapacity is the capability of the land to generate resources and absorb waste, while the ecological footprint is the amount of resources generated by a land that is needed to respond to human needs. 
## In our understanding, a country is unsustainable if the ecological footprint is higher than the biocapacity.


sustainability <- function(country_select) {
  

data<- read_csv("data/NFA 2019 public_data.csv")

## Creation 
sustain <- data %>% filter(record == "BiocapPerCap" | record == "EFConsPerCap") %>% group_by(year, country) %>% summarise(sustainablity = - diff(total))


Sbycountry <- filter(sustain, country == country_select)

plot <- ggplot(Sbycountry, mapping = aes(x = year, 
                             y = sustainablity)) +
  geom_histogram(stat = "identity") + 
  labs(title = paste("Sustainability per year for", country_select))

return(plot)

}
sustainability("Switzerland")

