library(dplyr)
library(ggplot2)
## Exploratory data analysis
## Looking at the data set, we realized that there are differente variables which we want to look deeper into : Biocapacity and Ecological footprint. 
## Biocapacity is the capability of the land to generate resources and absorb waste, while the ecological footprint is the amount of resources generated by a land that is needed to respond to human needs. 
## In our understanding, a country is unsustainable if the ecological footpring is higher than the biocapacity.


Biocap <- data %>% filter(record == "BiocapPerCap")
EFConsPerCap <- data %>% filter(record == "EFConsPerCap")

ggplot(Biocap, mapping = aes(x = year, 
                             y = total)) +
  geom_histogram(stat = "identity") + 
  labs(title = "Total Biocap per year")



