library(dplyr)
library(ggplot2)
library(tidyverse)
library(readr)


## Exploratory data analysis
## Looking at the data set, we realized that there are differente variables which we want to look deeper into : Biocapacity and Ecological footprint.
## Biocapacity is the capability of the land to generate resources and absorb waste, while the ecological footprint is the amount of resources generated by a land that is needed to respond to human needs.
## In our understanding, a country is unsustainable if the ecological footprint is higher than the biocapacity.

sustainability <- function(countries_select) {


data <- read_csv(here::here("data/NFA 2019 public_data.csv"))

## Creation
sustain <- data %>%
           filter(record == "BiocapPerCap" | record == "EFConsPerCap") %>%
           group_by(year, country) %>%
           summarise(sustainablity = - diff(total))

sustbycountry <- filter(sustain,
                        country %in% countries_select)

plot_countries <- ggplot(sustbycountry,
                         mapping = aes(x = year,
                                       y = sustainablity,
                                       fill = factor(country))) +

                  # Create bar plot
                  geom_bar(stat = "identity",
                           position = "dodge") +

                  labs(title = "Sustainability by country per year",
                       fill = "Country")

return(plot_countries)

}

countries <- list("China","Germany","India")

sustainability(countries)

